[versions]
kotlin = "2.2.21"
compose-multiplatform = "1.9.3"
jvm = "21"
agp = "8.11.2"
androidMinSdk = "24"
androidTargetSdk = "36"

[libraries]
androidAppCompat = "androidx.appcompat:appcompat:1.7.1"
androidActivityCompose = "androidx.activity:activity-compose:1.12.1"
androidMaterial = "com.google.android.material:material:1.13.0"
composeBackHandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "compose-multiplatform" }
kotlinCoroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
mavenPublish = "com.vanniktech.maven.publish:0.35.0"
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
