[versions]
kotlin = "2.3.10"
compose-multiplatform = "1.10.1"
jvm = "21"
agp = "8.13.2"
androidMinSdk = "24"
androidTargetSdk = "36"

[libraries]
androidAppCompat = "androidx.appcompat:appcompat:1.7.1"
androidActivityCompose = "androidx.activity:activity-compose:1.12.4"
androidMaterial = "com.google.android.material:material:1.13.0"
composeBackHandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "compose-multiplatform" }
composeFoundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose-multiplatform" }
composeUiTooling = "androidx.compose.ui:ui-tooling:1.10.3"
composeUiToolingPreview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "compose-multiplatform" }
composeRuntime = "androidx.compose.runtime:runtime:1.10.3"
composeMaterial = { group = "org.jetbrains.compose.material", name = "material", version.ref = "compose-multiplatform" }
composeMaterial3 = "org.jetbrains.compose.material3:material3:1.9.0"
composeMaterialIcons = "org.jetbrains.compose.material:material-icons-extended:1.7.3"
kotlinCoroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
mavenPublish = "com.vanniktech.maven.publish:0.36.0"
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
